"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import { useState } from "react";
import { ArrowRightLeft, Check, FileClock, Globe2, HeartHandshake, Mail, MapPin, Plane, Save, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { cities, countries, countryById } from "@/data/countries";
import { partners } from "@/data/marketplace";
import { pricing, services } from "@/data/content";
import { visaRoutes } from "@/data/visa-routes";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/section-heading";
import { VisaExplorer } from "@/components/visa-explorer";
import { BudgetCalculator } from "@/components/budget-calculator";
import { HousingMarketplace, JobsMarketplace } from "@/components/marketplaces";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function PageHero({ eyebrow, title, description, actions, visual }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode; visual?: React.ReactNode }) {
  return <section className="page-hero"><div className="container page-hero__grid"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p>{actions ? <div className="page-hero__actions">{actions}</div> : null}</div>{visual ?? <div className="page-hero__route"><MapPin /><span /><Plane /><span /><Globe2 /></div>}</div></section>;
}

export function DestinationsPage() {
  return <><PageHero eyebrow="Destination explorer" title="Find the place that fits the life you want." description="Compare lifestyle, housing, healthcare and everyday costs before you ask which immigration route may fit." actions={<Button asChild><Link href="/plan">Build my destination shortlist</Link></Button>} /><section className="section"><div className="container"><SectionHeading eyebrow="Launch destination" title="Vietnam, city by city" description="Illustrative costs help with planning; verify them before any decision." /><div className="destination-grid">{cities.slice(0, 3).map((city) => <Link href={`/destinations/vietnam/${city.id}`} className="destination-card" key={city.id}><div className="destination-card__image"><Image src={city.image} alt={`${city.name}, Vietnam`} fill sizes="(max-width: 800px) 90vw, 33vw" /></div><div className="destination-card__body"><div><Badge variant="review">Estimate</Badge><span>{money.format(city.monthlyBudget[0])}–{money.format(city.monthlyBudget[1])}/mo</span></div><h3>{city.name}</h3><p>{city.tagline}</p><ul>{city.highlights.map((item) => <li key={item}><Check /> {item}</li>)}</ul></div></Link>)}</div></div></section><section className="section section--alt" id="compare"><div className="container"><SectionHeading eyebrow="Compare my options" title="Facts according to your priorities" description="Country comparisons stay factual and avoid simplistic legal rankings." /><div className="comparison-table" role="region" aria-label="Destination comparison" tabIndex={0}><table><thead><tr><th>Destination</th><th>Immigration data</th><th>Living-cost data</th><th>Healthcare</th><th>Work possibilities</th><th>Launch status</th></tr></thead><tbody>{countries.slice(0, 6).map((country) => <tr key={country.id}><th>{country.flag} {country.name}</th><td>{country.launch ? "Source-linked route cards" : "General information only"}</td><td>{country.id === "vietnam" ? "City estimates available" : "Not yet modeled"}</td><td>Professional local review</td><td>Case and authorization dependent</td><td><Badge variant={country.launch ? "available" : "default"}>{country.launch ? "Launch" : "Coming soon"}</Badge></td></tr>)}</tbody></table></div></div></section></>;
}

export function DestinationPage({ countryId, cityId }: { countryId: string; cityId?: string }) {
  const country = countryById(countryId);
  const city = cities.find((item) => item.id === cityId);
  if (city) return <><PageHero eyebrow={`${country.flag} ${country.name}`} title={`Could ${city.name} be your next home?`} description={city.tagline} visual={<div className="page-hero__photo"><Image src={city.image} alt={`${city.name}, Vietnam`} fill sizes="45vw" priority /></div>} actions={<><Button asChild><Link href={`/results?origin=usa&destination=${country.id}&goal=retire&monthlyBudget=4000&relocationBudget=100000`}>Build this move</Link></Button><Button asChild variant="secondary"><Link href="/housing">Explore housing</Link></Button></>} /><section className="section"><div className="container city-detail-grid"><div><p className="eyebrow">Lifestyle brief</p><h2>A practical starting point</h2><p>{city.tagline} The figures below are mock estimates for product demonstration.</p><div className="city-detail-stats"><div><span>Monthly planning range</span><strong>{money.format(city.monthlyBudget[0])}–{money.format(city.monthlyBudget[1])}</strong></div><div><span>Housing starting point</span><strong>$800–$1,600 / month</strong></div><div><span>Healthcare</span><strong>International options available</strong></div><div><span>Connectivity</span><strong>Regional and international links</strong></div></div></div><aside><Badge variant="review">Illustrative estimate</Badge><h3>Why people shortlist {city.name}</h3><ul>{city.highlights.map((item) => <li key={item}><Check /> {item}</li>)}</ul><p>Visa and residence options are assessed separately from city fit.</p></aside></div></section><section className="section section--alt"><div className="container"><BudgetCalculator /></div></section></>;
  return <><PageHero eyebrow={`${country.flag} Destination guide`} title={`Move to ${country.name}`} description={country.launch ? "Explore launch-ready city, budget, service and immigration-planning information." : "General relocation information is being prepared. No visa eligibility is inferred for this destination."} actions={<Button asChild><Link href={`/plan?destination=${country.id}`}>Plan a move to {country.name}</Link></Button>} /><section className="section"><div className="container"><SectionHeading eyebrow={country.launch ? "Detailed launch data" : "Coming soon"} title={country.launch ? "Choose your starting city" : "This destination is not yet fully modeled"} />{country.id === "vietnam" ? <div className="city-comparison">{cities.map((item) => <Link href={`/destinations/vietnam/${item.id}`} key={item.id}><MapPin /><h3>{item.name}</h3><p>{item.tagline}</p></Link>)}</div> : <div className="empty-state"><Globe2 /><h3>General relocation information only</h3><p>Join the planning flow to record this destination without receiving invented visa advice.</p></div>}</div></section></>;
}

export function ServicesPage({ serviceId }: { serviceId?: string }) {
  const service = services.find((item) => item.id === serviceId);
  if (service) return <><PageHero eyebrow="Relocation service" title={service.name} description={service.note} actions={<Button asChild><Link href={`/contact?service=${service.id}`}>Add this service to my move</Link></Button>} visual={<div className="service-hero-icon"><service.icon /></div>} /><section className="section"><div className="container service-detail"><div><p className="eyebrow">What we coordinate</p><h2>One service, connected to the whole move</h2><p>Scope, provider qualifications, third-party fees and any regulated advice are confirmed before engagement.</p><ul>{["Needs review and practical brief", "Qualified partner or internal coordinator", "Milestones in your move dashboard", "Quotes, documents and decisions in one place", "Escalation to your relocation manager"].map((item) => <li key={item}><Check /> {item}</li>)}</ul></div><aside><Badge variant="premium">Move service</Badge><h3>Ready to include {service.name.toLowerCase()}?</h3><p>Build the complete move first so this service fits the right route, city, budget and date.</p><Button asChild variant="gold"><Link href="/plan">Build my move</Link></Button></aside></div></section></>;
  return <><PageHero eyebrow="Service marketplace" title="One company for your whole international move." description="Select only what you need. Every service stays connected to your route, budget, timeline and relocation manager." actions={<Button asChild><Link href="/plan">Build my service plan</Link></Button>} /><section className="section"><div className="container"><div className="service-grid">{services.map((item) => <Link href={`/services/${item.id}`} className="service-card" key={item.id}><span><item.icon /></span><h3>{item.name}</h3><p>{item.note}</p></Link>)}</div></div></section></>;
}

export function VisasPage({ countryId, visaId }: { countryId?: string; visaId?: string }) {
  const route = visaRoutes.find((item) => item.id === visaId);
  if (route) return <><PageHero eyebrow={`${route.destinationCountry.toUpperCase()} route information`} title={route.routeName} description={route.summary} actions={<Button asChild><Link href="/contact?topic=route-review">Request professional review</Link></Button>} visual={<div className="visa-code"><ShieldCheck /><strong>{route.routeCode}</strong><Badge variant="review">{route.status.replaceAll("_", " ")}</Badge></div>} /><section className="section"><div className="container visa-detail"><div><p className="eyebrow">Route facts</p><h2>What this category may involve</h2><dl><div><dt>Purpose</dt><dd>{route.category}</dd></div><div><dt>Typical duration</dt><dd>{route.typicalDuration}</dd></div><div><dt>Employer required</dt><dd>{route.employerRequired === null ? "Professional review" : route.employerRequired ? "Yes / category dependent" : "No"}</dd></div><div><dt>Work authorization</dt><dd>{route.workAllowed === null ? "Professional review" : route.workAllowed ? "Route dependent" : "No"}</dd></div><div><dt>Fees</dt><dd>{route.governmentFees}</dd></div><div><dt>Processing</dt><dd>{route.estimatedProcessingTime}</dd></div></dl></div><aside><Badge variant="available">Official source</Badge><h3>Last verified {route.lastVerified}</h3>{route.officialSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label}</a>)}<p>{route.disclaimer}</p></aside></div></section></>;
  return <><PageHero eyebrow="Visa & immigration explorer" title="Start with your life goal—not a visa code." description="Review potential categories in plain language, check source dates and see exactly where professional judgment is required." actions={<Button asChild><Link href="/plan">Assess my move</Link></Button>} /><section className="section"><div className="container"><VisaExplorer destination={countryId ?? "vietnam"} /></div></section></>;
}

export function PricingPage() {
  return <><PageHero eyebrow="Pricing" title="Choose how much of the move you want us to coordinate." description="Begin with an assessment, then add the level of execution and human support your move actually needs." /><section className="section"><div className="container"><div className="pricing-grid">{pricing.map((tier) => <article key={tier.name} className={tier.featured ? "is-featured" : ""}>{tier.featured ? <Badge variant="premium">Most complete</Badge> : null}<h3>{tier.name}</h3><strong>{tier.price}</strong><p>{tier.lead}</p><ul>{tier.features.map((item) => <li key={item}><Check /> {item}</li>)}</ul><Button asChild variant={tier.featured ? "gold" : "secondary"}><Link href={`/contact?plan=${tier.name}`}>Choose {tier.name}</Link></Button></article>)}</div><p className="pricing-disclaimer">Pricing is configurable and illustrative. Government, legal, moving, travel, property and third-party fees are separate unless quoted in writing.</p></div></section></>;
}

const intentContent: Record<string, { eyebrow: string; title: string; description: string; cards: [string, string][] }> = {
  retire: { eyebrow: "Retirement relocation", title: "Retire somewhere your life goes further.", description: "Compare everyday costs, healthcare, housing, climate, community and potential lawful long-stay routes without pretending a lifestyle fit equals visa eligibility.", cards: [["Destination fit", "Compare city pace, climate, community and connectivity."], ["Long-stay planning", "Map potential lawful route categories for professional review."], ["Healthcare", "Plan insurance, providers and continuity of care."], ["Housing", "Shortlist neighborhoods and temporary-to-long-term options."]] },
  work: { eyebrow: "International work", title: "Don’t just find a country. Find your opportunity there.", description: "Connect your career story, target roles, sponsorship facts and relocation plan.", cards: [["Career positioning", "Localize your CV and job-search strategy."], ["Sponsorship signals", "Separate yes, no, possible and unknown."], ["Route coordination", "Keep immigration review distinct from job matching."], ["Arrival", "Connect the job to housing, banking and local setup."]] },
  invest: { eyebrow: "Investor relocation", title: "Move capital and life with separate, qualified advice.", description: "Coordinate business establishment, investment review, banking, accounting, family relocation and professional immigration advice.", cards: [["Route review", "Never assume residency solely from investment."], ["Business setup", "Coordinate structure, licences and local operations."], ["Family move", "Connect schools, housing and dependent planning."], ["Specialist network", "Bring in regulated legal, tax and financial professionals."]] },
  family: { eyebrow: "Family relocation", title: "A move plan that works for the whole household.", description: "Put partners, children, parents, schools, pets and housing into the plan from day one.", cards: [["Family routes", "Screen relationship-based categories for professional review."], ["Schools", "Compare calendars, fees and commute."], ["Housing", "Match bedrooms, pets and neighborhood priorities."], ["Settling support", "Coordinate healthcare, utilities and daily life."]] },
  study: { eyebrow: "Study abroad", title: "Build the life around the education decision.", description: "Connect study authorization, housing, finances, family and the practical arrival checklist.", cards: [["Program fit", "Clarify institution, course and timeline."], ["Study route", "Review official requirements and professional support."], ["Housing", "Plan temporary and term-time accommodation."], ["Arrival", "Coordinate banking, phone, insurance and orientation."]] },
  business: { eyebrow: "Business relocation", title: "Build the company and the move together.", description: "Coordinate company setup, workspace, hiring, banking, accounting and the personal relocation journey.", cards: [["Market entry", "Define the operating model and local partners."], ["Company setup", "Coordinate qualified legal and accounting support."], ["Team", "Plan hiring, transfer and onboarding."], ["Personal move", "Keep home, family and immigration workstreams aligned."]] },
};

export function IntentPage({ type }: { type: string }) {
  const content = intentContent[type] ?? intentContent.retire;
  return <><PageHero eyebrow={content.eyebrow} title={content.title} description={content.description} actions={<><Button asChild><Link href={`/plan?goal=${type}`}>Build my {type} move</Link></Button><Button asChild variant="secondary"><Link href="/destinations">Compare destinations</Link></Button></>} /><section className="section"><div className="container"><div className="intent-grid">{content.cards.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{description}</p></article>)}</div></div></section><section className="section section--alt"><div className="container"><BudgetCalculator /></div></section></>;
}

export function CorporatePage() {
  return <><PageHero eyebrow="Corporate relocation" title="Relocate one employee—or one hundred—with one accountable program." description="Coordinate immigration, work permits, moving, housing, schools, onboarding, destination orientation and consolidated reporting." actions={<Button asChild><Link href="/contact?topic=corporate">Relocate my team</Link></Button>} visual={<div className="corporate-visual"><UsersRound /><span>1</span><i /><span>10</span><i /><span>100+</span></div>} /><section className="section"><div className="container"><div className="intent-grid">{[["Employee experience", "One dashboard, clear tasks and a human manager."], ["HR visibility", "Status, dates, exceptions and vendor coordination."], ["Compliance handoffs", "Qualified professionals handle regulated work."], ["Corporate billing", "Configurable packages and consolidated reporting."]].map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{description}</p></article>)}</div></div></section></>;
}

export function PartnersPage() {
  return <><PageHero eyebrow="Professional network" title="Local specialists, connected to one move plan." description="Partner cards in this demo are fictional and clearly labeled. Production profiles require identity, qualification and compliance checks." /><section className="section"><div className="container partner-grid">{partners.map((partner) => <article key={partner.name}><div><Badge variant="review">Mock partner</Badge><Badge variant="available">Verified demo state</Badge></div><h2>{partner.name}</h2><p>{partner.service}</p><dl><div><dt>Country</dt><dd>{partner.country}</dd></div><div><dt>Languages</dt><dd>{partner.languages}</dd></div><div><dt>Response</dt><dd>{partner.response}</dd></div></dl><Button variant="secondary">Request quote</Button></article>)}</div></section></>;
}

export function AboutPage() {
  return <><PageHero eyebrow="About LiveAnywhere Consulting" title="Relocation should feel understandable before it feels overwhelming." description="Relocate Anywhere Network is the planning and coordination platform operated by LiveAnywhere Consulting, beginning with USA ↔ Vietnam." /><section className="section"><div className="container about-grid"><div><p className="eyebrow">Our principle</p><h2>Tell us where you are today and where you want your life to go.</h2><p>We organize the route across immigration, documents, moving, home, work and daily life—then connect qualified people where judgment matters.</p></div><div className="support-model"><article><span><Sparkles /></span><h3>Clear planning</h3><p>A life-first experience instead of a wall of visa codes.</p></article><article><span><HeartHandshake /></span><h3>Human accountability</h3><p>One relocation manager across the moving parts.</p></article><article><span><ShieldCheck /></span><h3>Professional boundaries</h3><p>Legal, tax and regulated decisions stay with qualified professionals.</p></article></div></div></section></>;
}

export function ContactPage() {
  const [sent, setSent] = useState(false);
  return <><PageHero eyebrow="Talk to a relocation manager" title="Bring us the life you want to build." description="We’ll organize the move, identify where professional review is needed and give you one clear next step." /><section className="section"><div className="container contact-grid"><form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><div className="form-grid"><label><span>Name</span><input required name="name" /></label><label><span>Email</span><input required type="email" name="email" /></label><label><span>Origin</span><select name="origin">{countries.map((country) => <option key={country.id}>{country.name}</option>)}</select></label><label><span>Destination</span><select name="destination">{countries.map((country) => <option key={country.id}>{country.name}</option>)}</select></label><label className="full"><span>What do you want your move to achieve?</span><textarea required rows={5} name="message" /></label><label className="check-field full"><input type="checkbox" required /><span>I agree to be contacted about this relocation request.</span></label></div><Button type="submit"><Mail /> Send my request</Button>{sent ? <p className="success-message" role="status"><Check /> Demo request recorded locally. Connect a production CRM or email service before launch.</p> : null}</form><aside><Badge variant="premium">Human support</Badge><h2>Your relocation manager can coordinate</h2><ul>{["Chat, phone or video appointment", "Document-metadata review", "Licensed professional referral", "Property and recruiter request", "Move quotes and partner follow-up"].map((item) => <li key={item}><Check /> {item}</li>)}</ul></aside></div></section></>;
}

export function AdminPage() {
  const [selected, setSelected] = useState(visaRoutes[0].id);
  const [saved, setSaved] = useState(false);
  const route = visaRoutes.find((item) => item.id === selected)!;
  return <><PageHero eyebrow="Admin demo" title="Keep time-sensitive relocation information accountable." description="This development surface demonstrates source dates, review states and audit requirements. Production access must be role-gated." /><section className="section"><div className="container admin-layout"><aside><h2>Content</h2>{["Countries", "Cities", "Visa routes", "Official sources", "Properties", "Jobs", "Partners", "Pricing", "Customers", "Audit log"].map((item) => <button className={item === "Visa routes" ? "is-active" : ""} key={item}>{item}</button>)}</aside><div className="admin-panel"><div className="panel-head"><div><p className="eyebrow">Visa route editor</p><h2>Verification and source controls</h2></div><Badge variant="review">Demo only</Badge></div><label><span>Select route</span><select value={selected} onChange={(event) => { setSelected(event.target.value); setSaved(false); }}>{visaRoutes.map((item) => <option key={item.id} value={item.id}>{item.destinationCountry.toUpperCase()} · {item.routeName}</option>)}</select></label><div className="admin-form"><label><span>Public title</span><input defaultValue={route.routeName} key={`${route.id}-name`} /></label><label><span>Status</span><select defaultValue={route.status} key={`${route.id}-status`}><option>ACTIVE</option><option>REQUIRES_REVIEW</option><option>PROPOSED</option><option>SUSPENDED</option><option>CLOSED</option></select></label><label><span>Last verified</span><input type="date" defaultValue={route.lastVerified} key={`${route.id}-date`} /></label><label><span>Official source</span><input defaultValue={route.officialSources[0].url} key={`${route.id}-url`} /></label><label className="full"><span>Change reason</span><textarea rows={4} placeholder="Required for the audit log" /></label></div><div className="admin-warning"><FileClock /><p>Every production change should record the user, old value, new value, timestamp and official source.</p></div><Button onClick={() => setSaved(true)}><Save /> {saved ? "Demo change saved" : "Save with audit record"}</Button></div></div></section></>;
}

export function SignInPage() {
  const router = useRouter();
  const [email, setEmail] = useState("demo@liveanywhere.consulting");
  const [password, setPassword] = useState("DemoMove2027!");
  const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError("");
    const result = await signIn("credentials", { email, password, redirect: false });
    if (result?.error) setError("Use the supplied demo credentials or configure your environment values.");
    else router.push("/dashboard");
  };
  return <section className="sign-in-page"><form onSubmit={submit}><Badge variant="possible">Demo access</Badge><h1>Welcome back</h1><p>Open your move dashboard and continue where you left off.</p><label><span>Email</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label><span>Password</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error ? <p className="form-error">{error}</p> : null}<Button type="submit">Sign in</Button><small>Demo credentials are prefilled. Replace them before production.</small></form></section>;
}

export function MoveRoutePage({ originId, destinationId }: { originId: string; destinationId: string }) {
  const origin = countryById(originId);
  const destination = countryById(destinationId);
  const reverseGoal = destinationId === "usa" ? "work" : "retire";
  return <><PageHero eyebrow="Popular move" title={`${origin.flag} ${origin.name} to ${destination.flag} ${destination.name}`} description={`Build a personalized ${origin.shortName} → ${destination.shortName} journey across immigration, moving, home, work and daily life.`} actions={<Button asChild><Link href={`/results?origin=${originId}&destination=${destinationId}&goal=${reverseGoal}&people=2&monthlyBudget=4000&relocationBudget=100000&timeframe=3-6-months&duration=permanent`}>Build this move</Link></Button>} visual={<div className="route-pair-visual"><span>{origin.flag}</span><ArrowRightLeft /><span>{destination.flag}</span></div>} /><section className="section"><div className="container"><SectionHeading eyebrow="What your plan will include" title="A complete route—not a visa search" /><div className="intent-grid">{[["Immigration", "Potential route categories with sources and review states."], ["Move budget", "Flights, logistics, deposits, setup and buffer."], ["City fit", "Lifestyle, housing and everyday-cost comparison."], ["Execution", "Tasks from documents through arrival and settling."]].map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{description}</p></article>)}</div></div></section></>;
}

export function SeoIntentPage({ slug }: { slug: string }) {
  const vietnam = slug.includes("vietnam");
  const usa = slug.includes("usa") || slug.includes("americans");
  const type = slug.startsWith("retire") ? "retire" : slug.startsWith("work") ? "work" : slug.startsWith("invest") ? "invest" : "move";
  const destination = vietnam ? "Vietnam" : usa ? "United States" : "your destination";
  return <><PageHero eyebrow={`${type} in ${destination}`} title={`Plan your ${type === "move" ? "move" : type} in ${destination} around the life you want.`} description="Start with origin, destination, household, goal, date and budget. The platform organizes potential routes and practical services without making eligibility promises." actions={<Button asChild><Link href="/plan">Build my move</Link></Button>} /><section className="section"><div className="container seo-content"><Badge variant="review">Professional review required</Badge><h2>What this planning page can—and cannot—do</h2><p>It can organize general information, source-linked route categories, destination fit and illustrative costs. It cannot guarantee a visa, green card, job or legal outcome.</p><div className="intent-grid">{[["Tell us your goal", "Use life language, not unfamiliar visa codes."], ["See the route", "Connect immigration, documents, home, work and arrival."], ["Check sources", "Use official links and verification dates."], ["Meet the team", "Escalate regulated decisions to qualified professionals."]].map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section></>;
}

export function NotFoundContent() {
  return <section className="not-found"><Search /><p className="eyebrow">Route not found</p><h1>This page is not part of the move yet.</h1><p>Return home or start a relocation plan.</p><div><Button asChild><Link href="/">Go home</Link></Button><Button asChild variant="secondary"><Link href="/plan">Plan my move</Link></Button></div></section>;
}

export { HousingMarketplace, JobsMarketplace };
